"""Prompt engineering and ChatML formatting templates for FinSLM.

💡 Learning Concepts & References:
- What is Prompt Engineering? Crafting specific instructions that guide AI models to produce accurate outputs.
- 📖 GFG Guide: https://www.geeksforgeeks.org/prompt-engineering/
- What is ChatML? A standard messaging schema invented by OpenAI to distinguish System, User, and Assistant roles.
  - 'system': Sets the model's persona, boundaries, and rules.
  - 'user': The question asked by the human.
  - 'assistant': The answer generated by the model.
- 📖 Reference: https://github.com/openai/openai-python/blob/main/chatml.md
"""

from src.core.schemas import FinancialTaskType

# Master System Prompt defining the AI's identity and reasoning rules
SYSTEM_PROMPT_CORE = """You are FinSLM, an enterprise financial AI assistant with expertise in corporate finance, SEC filings, financial mathematics, Text-to-SQL, and compliance.

Core Rules:
1. Precision: Never guess numbers. Always verify formulas before outputting.
2. Structured Reasoning: Provide step-by-step reasoning inside <thought>...</thought> tags before giving the final answer.
3. SQL Safety: For database queries, output clean, read-only SQL enclosed in ```sql ... ``` code blocks.
4. Professional Tone: Deliver executive-ready financial insights with clear caveats if data is incomplete.
"""

SYSTEM_PROMPT_SQL = """You are FinSLM specialized in Financial Text-to-SQL.
Given a database schema and a natural language question:
1. Identify tables and join conditions in <thought>...</thought>.
2. Generate a valid, read-only SQL query inside ```sql ... ```.
3. Explain the query briefly.
"""


def get_system_prompt(task_type: FinancialTaskType = FinancialTaskType.GENERAL_FINANCE) -> str:
    """Return the system prompt appropriate for the given financial task.
    
    Why use task-specific system prompts?
    - A model instructed specifically on SQL rules generates much fewer syntax errors
      than one using a generic conversational prompt.
    """
    if task_type == FinancialTaskType.TEXT_TO_SQL:
        return SYSTEM_PROMPT_SQL
    return SYSTEM_PROMPT_CORE


def build_chatml_messages(
    query: str,
    task_type: FinancialTaskType = FinancialTaskType.GENERAL_FINANCE,
    context: str | None = None,
) -> list[dict[str, str]]:
    """Build standard Hugging Face ChatML messages dictionary list.
    
    Example Output:
    [
        {"role": "system", "content": "You are FinSLM..."},
        {"role": "user", "content": "Calculate the WACC for Company X..."}
    ]
    """
    system_prompt = get_system_prompt(task_type)
    user_content = query
    if context:
        user_content = f"### Reference Context / Schema:\n{context}\n\n### User Query:\n{query}"

    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_content},
    ]
